services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: cf-saas-backend-php
    working_dir: /app
    volumes:
      - .:/app
      - vendor_data:/app/code/vendor
      - framework_cache:/app/code/storage/framework
      - logs_data:/app/code/storage/logs
      - bootstrap_cache:/app/code/bootstrap/cache
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME:-commandaflow_saas}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-secret}
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
      - backend

  web:
    image: nginx:latest
    container_name: cf-saas-backend-web
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: cf-saas-backend-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME:-commandaflow_saas}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cf-saas-backend-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS:-secret}
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cf-saas-backend-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - backend

volumes:
  postgres_data:
  vendor_data:
  framework_cache:
  logs_data:
  bootstrap_cache:

networks:
  backend:
    driver: bridge
 